## Travis CI Integration

notifications:
  email: false
  irc: "chat.freenode.net#d.mono-d"

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

language: csharp
mono: none
dotnet: 3.1.103
solution: LSP4D.sln
cache: bundler

install:
  - cd LSP4D
  - dotnet restore

script:
  - dotnet build /p:Configuration=Debug "/p:Platform=Any CPU"
  - dotnet test ./DParserverTests/bin/Debug/netcoreapp3.1/DParserverTests.dll
